### ISSUE TITLE
Chin Intro

### ISSUE THREAD

**Issue by jobin-johnson-22** [mspkarunya/frstone#52]
Chin is a good boy and studious one

**Comment by darkslade9** [comment]
heyyo,ur name is jobin too huh?whatta coindidence

**Comment by RichardTimothy1307** [comment]
chin u know jobin will take our college to greater heights uptill iit nahhh MIT level

**Comment by darkslade9** [comment]
our college has already reached a new level after he ahs joined,the sky is the limit now

**Comment by jobin-johnson-22** [comment]
haa....... bhai log thank u 4 the appreciation....

**Comment by RichardTimothy1307** [comment]
not it has reached parellel universe also
his achievements are travellling upto the speed of TACHYONS

**Comment by darkslade9** [comment]
tbh,i feel the same,ever since i first laid eyes on him my mind has been split into different realms

**Comment by RichardTimothy1307** [comment]
JOBIN is inventor of space time coding relativity 
he is the founder of QUARKS in Coding and hacking

**Comment by darkslade9** [comment]
he invented the space time continuum and he continues to tear it too,i once saw him use a blackhole as a toilet bowl.

**Comment by RichardTimothy1307** [comment]
where does his stool gets flushed or deposited

**Comment by darkslade9** [comment]
idk,prob only God and him know.
